### ISSUE TITLE
Enhancement: Add XEP-0333 Chat Markers support

### ISSUE THREAD

**Issue by nickbroon** [legastero/stanza.io#114]
Lots of chat apps (Facebook Messenger, Hangouts, Slack) support showing marker of how far a client has read. XEP-0333 Chat Markers provides similar capabilities.
http://conversations.im/ Android XMPP client makes use of this.
It would be great to see Stanza.io provide support for this, and to eventually then see it exposed in otalk-im-client/kaiwa.

**Comment by wiktor-k** [comment]
@legastero I think this ticket can be closed as Chat Markers support has been merged in PR #283.
