### ISSUE TITLE
ICE discovery status

### ISSUE THREAD

**Issue by wmfairuz** [legastero/stanza.io#123]
Hi,

Let say after calling `client.discoverICEServers()` the server returns a set of STUN/TURN server list for the client to use.

I assume this list will be used when it tries to initiate a connection between two endpoints?

Can we know if these servers successfully or failed to resolve the connection on both ways? Or will it just silently fails and the user will just see a black video stream.

Thanks.

**Comment by legastero** [comment]
> I assume this list will be used when it tries to initiate a connection between two endpoints?

Correct

> Can we know if these servers successfully or failed to resolve the connection on both ways? Or will it just silently fails and the user will just see a black video stream.

You can inspect `jingleSession.connectionState` to see if it has connected or failed.

**Comment by wmfairuz** [comment]
@legastero thanks!

**Comment by wmfairuz** [comment]
An additional question if you don't mind.

From what I understand the session object will be shared between those two parties. Is this correct?

Does that mean the value of connectionState should be the same for both parties?

Before this, what I understand is, the connection is 2 ways, which means that if A can see B's stream, it doesn't mean B can see A's stream.
