### ISSUE TITLE
stanza.io without node js 

### ISSUE THREAD

**Issue by rashkat** [legastero/stanza.io#141]
Hello

Can we use stanza.io as pure javascript library. We do not need node support. If yes please guide how to setup it without npm.

Regards
Rashmi

**Comment by vitalyster** [comment]
npm is only used to fetch dependencies, run `make build` in source tree and you will get `stanzaio.bundle.js` which is perfectly run in browser

**Comment by rashkat** [comment]
Thanks. Got it running.
