### ISSUE TITLE
Can't send message to MUC

### ISSUE THREAD

**Issue by Ghost-cruiser** [legastero/stanza.io#148]
Hi,

Each time I try to send a message to a MUC, I receive a 400 error. The MUC did trigger the 'muc:join' event. Here are the raw exchanges : 

![image](https://cloud.githubusercontent.com/assets/17065525/14959220/99918eba-108e-11e6-940b-7fdd8ce04f02.png)

The 'muc:error' is not triggered

Have you an idea about what prevents the communication? 

Thanks in advance!

**Comment by axelson** [comment]
How are you sending?

`client.sendMessage({to: room, body: 'message text', type: 'groupchat'})` is working for me

**Comment by Ghost-cruiser** [comment]
My apologies, I forgot to come back to close this : I was not adding the { type: 'groupchat' } needed for the message.

Again sorry, and thank you for your time!

**Comment by Froelund** [comment]
@Ghost-cruiser Can you close the issue?
