### ISSUE TITLE
custom field in message stanza

### ISSUE THREAD

**Issue by denkomanceski** [legastero/stanza.io#161]
Is it possible to add a custom field in the message stanza which later we can use for something? And when we fetch the messages from history that field should also exist in the message

Regards

**Comment by sarumjanuch** [comment]
Prosody do save whole stanza with custom attrs etc....  yes, it is, but you need to extend message with you custom tag/field/attr/namespace etc.. 

https://github.com/legastero/stanza.io/issues/143

**Comment by ksarkar123** [comment]
How to call our plugins
