### ISSUE TITLE
mamResult empty?

### ISSUE THREAD

**Issue by Jom4nJi** [legastero/stanza.io#163]
Whenever I call `client.searchHistory` the _items_ object inside of _mamResult_ is always empty no matter what. Why does this happen? Is this my servers' fault or my client's?

**Comment by thesabbir** [comment]
is openfire is your backend?

**Comment by Jom4nJi** [comment]
I'm using ejabberd. Here is my code:

```
client.searchHistory({
            with: currentUser,
            rsm: {
                max: 50
            }
        }, function(sender, result) {
            console.log(result);
        });
```

**Comment by thesabbir** [comment]
Simply Try:
```js
client.searchHistory(
{ with: 'jid@server.xyz'
})
.then(function (mam) {
console.log(mam.mamResult.items);
})

```
Also log any raw incoming.

**Comment by Jom4nJi** [comment]
Hmm... I seem to get this error with your code:
`main.html:156 Uncaught TypeError: Cannot read property 'then' of undefined`
Also, how do I log raw incoming?

**Comment by thesabbir** [comment]
```js
client.on('*', function(data) {
 console.log(data);
})
```
or
```js
client.on('raw:*', function(data) {
 console.log(data);
})
```

**Comment by Jom4nJi** [comment]
Here is my raw log: http://pastebin.com/c2CEYvy6

**Comment by Jom4nJi** [comment]
well that explains it, I didn't make sure the users' subscription is **both**
