### ISSUE TITLE
Extending Presence with Plugin isn't working

### ISSUE THREAD

**Issue by zacharyabresch** [legastero/stanza.io#165]
Hi! I'm working on a plugin to extend the `Presence` object and can't seem to get it working. Our XMPP server sends a customized presence stanza containing an element (the **2** can be several numeric values):

```
<presenceValue>2</presenceValue>
```

Here's my plugin code:

```
import PresenceMap from '../../el/helper/PresenceMap';
import { xmppLog as log } from '../helpers/log';

module.exports = (client, stanzas) => {
  const types = stanzas.utils;

  const PresenceExt = stanzas.define({
    name: 'PresenceExt',
    element: 'presenceValue',
    fields: {
      text: types.text(),
    },
  });

  stanzas.withPresence(Presence => {
    stanzas.extend(Presence, PresenceExt);
  });

  client.on('presence', presence => {
    log.info({ presence }, 'Custom Presence');
  });
};
```

The `log` is `bunyan`, BTW. Anyway, when logging out presence in the handler for the `presence` event, I am not receiving the `presenceValue` as expected.

I am loading the plugin according to the docs:

```
client.use(
  require('../stanzaio-plugins/CustomPresence') // eslint-disable-line global-require
);
```

I could be missing something here so please let me know what you think is going on. If you need any other code or sample data please let me know.

This has been a blocker for me for days so _any_ help would be greatly appreciated!

Thanks and cheers!

**Comment by legastero** [comment]
You have to specify the namespace for the element in the `define()` call.

If your server is not including an `xmlns` attribute for that element (but it should!), then you'll need to use `'jabber:client'` to match the namespace of the `<presence />` stanza.

**Comment by zacharyabresch** [comment]
Thanks for the tip @legastero. I was able to add this custom element to the native `presence` object. Unfortunately, it is now **overwriting** the native presence object. Here's some code to show what I'm talking about:

## Example Stanzas

### "Available"
```
<presence xmlns="jabber:client" from="username@hostname.com" to="username@hostname.com/c3a96e1b-cff3-4d82-9f12-5caa7e75e8ad"><presenceValue>2</presenceValue><x xmlns="vcard-temp:x:update"><photo></photo></x></presence>
```

### "Unavailable"
```
<presence xmlns="jabber:client" from="username@hostname.com" to="username@hostname.com/c3a96e1b-cff3-4d82-9f12-5caa7e75e8ad" type="unavailable"><status></status><presenceValue>0</presenceValue><x xmlns="vcard-temp:x:update"><photo></photo></x></presence>
```

## Plugin Code

```
import PresenceMap from '../../el/helper/PresenceMap';
import { xmppLog as log } from '../helpers/log';

module.exports = (client, stanzas) => {
  const types = stanzas.utils;

  const PresenceExt = stanzas.define({
    name: 'presence',
    namespace: 'jabber:client',
    element: 'presence',
    fields: {
      presenceValue: types.textSub('jabber:client', 'presenceValue'),
    },
  });

// I tried both of the approaches below and neither affected the outcome
  const Presence = stanzas.getPresence();
  stanzas.extend(Presence, PresenceExt);

  // stanzas.withPresence(Presence => {
  //   stanzas.extend(Presence, PresenceExt);
  // });

  client.on('presence', presence => {
    log.warn({ presence }, 'Custom Presence');
  });
};
```

## Output from logging `presence`

### Available
```
presence: {
  "lang": "en",
  "presenceValue": "2"
}
```

### Unavailable
```
presence: {
  "lang": "en",
  "presenceValue": "0"
}
```

---

So, as you can see, I'm finally getting the custom element ... but now all the other data associated with this presence event is discarded. Thoughts? I feel like I'm *so* close. :)

**Comment by legastero** [comment]
I meant that this should work:

```js
  const PresenceExt = stanzas.define({
    name: 'presenceExt',
    namespace: 'jabber:client', // <presenceValue /> is not using a custom namespace
    element: 'presenceValue',
    fields: {
      text: types.text(),
    },
  });
```

Giving you:

```js
presence: {
  "presenceExt": {
    "text": "2"
  }
}
```

Alternatively, to add just a single field you could use:

```js
stanzas.withPresence(Presence => {
    stanzas.add(Presence, 'presenceExt', types.textSub('jabber:client', 'presenceValue'));
});
```

Giving you:

```js
presence: {
  "presenceExt": "2"
}
```

**Comment by zacharyabresch** [comment]
@legastero Thank you ***so much***! I ended up going with the `.add` approach and it worked like a charm. I didn't see that documented or used anywhere so I didn't even know it existed. I'd recommend updating the docs to highlight this. If you want, I could add an example of how I used it. Let me know.

My final question is this, is there anyway to use the ES6 module import/export pattern for `stanza.io` plugins? The team would prefer to use one approach to this and are already using ES6 modules across the entire project. For example:

## `CustomPresence.js`
```
export default function (client, stanzas) {
  const types = stanzas.utils;
  stanzas.withPresence(Presence => {
    stanzas.add(Presence, 'presenceValue', types.textSub('jabber:client', 'presenceValue'));
    stanzas.add(Presence, 'exshow', types.textSub('jabber:client', 'exshow'));
  });
}
```

The thing I can't grok is how to then import this in the `client.use` method. So, right now I have:

```
client.use(
  require('../stanzaio-plugins/CustomPresence') // eslint-disable-line global-require
);
```

but I'd like to do something like:

```
import { CustomPresence } from '../stanzaio-plugins/CustomPresence';

client.use(
  CustomPresence
);
```

If I do the above, I get the error `pluginInit is not a function` in the console. Any thoughts on this?

Thanks for all of your help on this. Totally saved me this sprint. :)

**Comment by zacharyabresch** [comment]
I also tried `import CustomPresence from '../stanzaio-plugins/CustomPresence';` which also didn't work.

**Comment by zacharyabresch** [comment]
Okay ... so that last comment actually worked and our custom presence is now working perfectly. Thanks again and I'd say you can consider this issue closed.
