### ISSUE TITLE
https://stanza.io certificate issues

### ISSUE THREAD

**Issue by andreieftimie** [legastero/stanza.io#170]
Opening up https://stanza.io in Safari on OSX fails make a connection stating that Safari failed to initiate a secure connection (rough translation as I have OSX in a different language).

Chrome states that the certificate date is not valid: `NET::ERR_CERT_DATE_INVALID`

**Comment by legastero** [comment]
Thanks! I gave the letsencrypt cron script a kick, so this should be resolved now.
