### ISSUE TITLE
Reconnection to the same session after page refresh | Question

### ISSUE THREAD

**Issue by Ghost-cruiser** [legastero/stanza.io#174]
Hi,
I'm trying to reconnect my user to its opened rooms after a page refresh, but I can't figure out exactly how to do so (or if it is possible at all). I've tried to resume the session with sm and the sid, but it doesn't do anything (no response from the server).
Could you please indicate the steps to follow?

Config : stanza.io + openfire 4.0.2

Thanks in advance.

**Comment by Ghost-cruiser** [comment]
Once again, the answer was in xmpp specification!
(Just connect the normal way, the ask to resume sessions with client.sm.resume())

Thanks and sorry for any disturbance.

**Comment by purrado** [comment]
How can this be implemented with the latest version of stanza? I've tried resuming with `client.sm.resume()` to no avail. Any help would be great!

cc/ @legastero
