### ISSUE TITLE
How to extend presence with nested elements?

### ISSUE THREAD

**Issue by caisah** [legastero/stanza.io#175]
Hi,

I want to send a presence of the form:
```xml
<presence
    from='hag66@shakespeare.lit/pda'
    id='n13mt3l'
    to='coven@chat.shakespeare.lit/thirdwitch'>
  <x xmlns='http://jabber.org/protocol/muc'>
    <item name='John Doe' gun=’FP008832676267’ id='3A03206A-4058-41E9-805A-2C26AA371373'  max='15' flag='false' />
  </x>
</presence>
```
but I didn't find anywhere how to do it. I understand I have to define the stanza but I've seen no example using nested tags.

Could someone please point me in the right direction?

Thanks!

**Comment by sarumjanuch** [comment]
https://github.com/otalk/jxt-xmpp/blob/master/src/muc.js you can find examples here.
