### ISSUE TITLE
continuously outgoing requests to server 

### ISSUE THREAD

**Issue by edukondalugorla** [legastero/stanza.io#176]
Hi,  I have a problem in my chat client. My client is sending continuous outgoing requests to server. client is sending pockets like
`<body xmlns="http://jabber.org/protocol/httpbind">
<a xmlns="urn:xmpp:sm:3" h="0" />
</body>`

I am not understanding why client is making these requests. What is mean of this request. and how to stop these request to improve server perfomence. Please help me. Thanks,

**Comment by thesabbir** [comment]
What is your transport method? (Bosh or websocket)
