### ISSUE TITLE
How to create plugin?

### ISSUE THREAD

**Issue by sadstatue** [legastero/stanza.io#190]
Hi,

I want to implement XEP-0012: Last Activity

here's my plugin code (last.js)

```
'use strict';

module.exports = function (client) {

    client.disco.addFeature('jabber:iq:last');

    client.on('iq:get:last', function (iq) {
        client.sendIq(iq.resultReply({
            last: new Date().getTime()
        }));
    });

    client.getLastActivity = function (jid, cb) {
        return this.sendIq({
            to: jid,
            type: 'get',
            last: true
        }, cb);
    };


};
```
and then I use with `client.use(require('last'))`

but when I call `client.getLastActivity('id@vhost.com')` I got an Error bad request.

am I missing something? thanks

**Comment by legastero** [comment]
It looks like you still need to make the stanza definitions for XEP-0012. Everything else looks correct.

**Comment by sadstatue** [comment]
@legastero can you please show me how to make stanza definitions? thanks before..
