### ISSUE TITLE
client.jid is never set, only client.config.jid is set

### ISSUE THREAD

**Issue by ClaudiaStefan** [legastero/stanza.io#191]
I found this issue while debugging why the carbons were not working. In plugins in carbons.js, when **carbon:*** event is triggered, a check is made like this:

`if (carbon.from.bare !== client.jid.bare) {
return;
}
` 

I checked **client.jid.bare** and I saw that it is an empty string. When I checked **client.config.jid.bare**, it was the correct jid.

I checked client.js and noticed that **this.jid** is set in the cunstructor like this: 

`this.jid = new JID();` 

I haven't found a place where it is set again in the code, but there are plenty of places where there are checks agains **client.jid**. I haven't found a place were the checks were made agains **client.config.jid**.

I think this is a bug.

**Comment by legastero** [comment]
I'm assuming you're using BOSH with pre-binding.

Latest version now simulates JID binding when using a pre-bound BOSH connection. Let me know if that doesn't fix the issue.

**Comment by andreieftimie** [comment]
Using websockets

**Comment by ClaudiaStefan** [comment]
@legastero   I updated to version 8.1.0. We don't use BOSH with pre-binding. We are using websockets, xmpp and the issue is still persistent. 

I also found another issue in that carbon code (version 8.1.0):

`if (!msg.delay) {
            if (delay) {
                msg.delay.stamp = delay.stamp; // line 50 - If the check above would work, this would still fail as msg.delay is undefined`

**Comment by legastero** [comment]
What server are you using?

**Comment by ClaudiaStefan** [comment]
It is a custom server. I can't disclose more details about it.

**Comment by legastero** [comment]
Then your custom server is likely non-conforming and is not advertising resource binding like it should. See https://tools.ietf.org/html/rfc6120#section-7 for what it needs to do.

Once the server advertises binding, then [the bind plugin](https://github.com/legastero/stanza.io/blob/master/lib/plugins/bind.js) will kick in and set `client.jid` to the actual JID in use, including resource.

**Comment by ClaudiaStefan** [comment]
@legastero Thank you. I will check this out.
