### ISSUE TITLE
Odd disconnect after reconnect?

### ISSUE THREAD

**Issue by MattFoley** [legastero/stanza.io#203]
I've been using Stanza.io and it's been great, and lately I've been working on setting up reconnection management.

I have this almost working, but there's a slight hiccup that I can seem to pin down. After disconnecting, and then reconnecting, my user is then timed out after almost exactly 60s. On disconnect, I reuse the same client instance, and just call .connect() again. 

Reconnection kicks in again, and sometimes they're good to go, and sometimes they're disconnected again in 60s. This doesn't happen if I don't ever trigger a disconnect (just disabling/re-enabling wifi on my machine). All the while, I see successful acks from the server.

I'm using transport: 'websocket', and `useStreamManagement:true`, I'm also setting enableKeepAlive like this:
```
    this.client.enableKeepAlive({
      interval: 30
    });
```

I'm using an ejabberd backend, and I see logs like this that seem to correspond with the following disconnects:
```
Timed out waiting for resumption of stream for 5921012@chat.domain.com/4723934085512403596578
```

Am I missing something about how to reconnect with Stanza, or is this possibly an issue with my ejabberd configuration?

**Comment by MattFoley** [comment]
100% my fault. If anyone else runs into this issue, it's because you're connecting multiple times.

**Comment by andrewvmail** [comment]
@MattFoley I may have this issue but what do you mean connecting multiple time? do you need to call connect() at all?

**Comment by MattFoley** [comment]
I start out with `client.connect()` for setting up the socket connection, and there were cases where I was calling `client.connect()` twice without calling `client.disconnect()`
