### ISSUE TITLE
Why does stanza.io installation modify my project's package.json?

### ISSUE THREAD

**Issue by marcusegues** [legastero/stanza.io#219]
When I run npm install inside /node_modules/stanza.io, I get new files in my project's root directory: .jshintignore, .jshintrc. I also get some lines added to my package.json:
```  
"pre-commit": [
    "lint",
    "validate",
    "test"
  ]
"scripts": {
    (...),
    "lint": "jshint .",
    "validate": "npm ls"
```

It actually prevents me from committing on my project because the pre-commit lint command doesn't pass. 

Can I eliminate all these modifications?

**Comment by legastero** [comment]
Running `npm install` inside of `node_modules/` isn't really something you should do.

That said, using `npm install --production` will prevent installing the development dependencies that are adding those files, and those modifications can be safely eliminated.
