### ISSUE TITLE
Delete/Remove message/conversation

### ISSUE THREAD

**Issue by itsazzad** [legastero/stanza.io#222]
How to delete/remove message/conversation?

**Comment by legastero** [comment]
XMPP doesn't really support that kind of thing at the protocol level (yet), so neither does stanza.io.

**Comment by Sheharyar566** [comment]
Hi legastero, a new specification was recently released, though experimental, but is supposed to deal with message retractions. Can you please confirm whether it is in the to-do's list for implementations or not?
