### ISSUE TITLE
Cannot read property '_name' of undefined stanza.io

### ISSUE THREAD

**Issue by Robophil** [legastero/stanza.io#224]
Holla,
I'm getting this error when using stanza.io. This occurs after a connection has been established,
somewhere around this line https://github.com/legastero/stanza.io/blob/master/lib/transports/websocket.js#L68. At this point, `stanzaObj` is `undefined`, the content of **data** passed to `stanzas.parse(data)` is shown below
```xml
<stream:features xmlns="http://etherx.jabber.org/streams">
    <mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl">
        <mechanism>PLAIN</mechanism>
    </mechanisms>
</stream:features>
```

How can I get around this?

**Comment by legastero** [comment]
Your server is not following RFC 7395.

See https://github.com/legastero/stanza.io#important-protocol-changes

**Comment by Robophil** [comment]
Thanks, would check this out.
