### ISSUE TITLE
Plain sasl auth is failing in IE 11

### ISSUE THREAD

**Issue by dwilson6** [legastero/stanza.io#239]
@legastero It appears that this commit broke sasl auth in IE 11: https://github.com/legastero/stanza.io/commit/7fb610f8f348a7fcb8f0e3839e8e946210452d85

I pulled the latest stanza (8.4.8) and I am creating a Stanza.Client instance with plain auth and when I try to connect I get an auth:failed event and when I debugged it I found that no sasl mechanisms were loaded because existingMech.name is undefined. This worked on stanza 8.4.0. I am using browserify as my module loader/bundler.

What was existingMech.name supposed to check? Right now it is the function name which is 'Mechanism' in chrome and is undefined in IE. Maybe that line could either check if existingMech is a function or that existingMech.prototype.name is truthy to make sure it is loaded.

**Comment by legastero** [comment]
Ok, that check isn't working like I thought it was then.

The intent was to handle cases where those `require` calls don't actually load the module (from ignoring them via Webpack or browserify). With Browserify you can make it return `false`, but Webpack returns `{}`.

I'll get this patched sometime today or this weekend then. Thanks so much for the report!

**Comment by dwilson6** [comment]
Thanks! That fixed the issue
