### ISSUE TITLE
Immediate disconnect due to lack of SNI support when using a secure websocket transport (wss://) in node.js client

### ISSUE THREAD

**Issue by eldridge** [legastero/stanza.io#242]
I'm documenting this here in case others run into this issue.  I've been banging my head trying to figure out what I was doing wrong.  Turns out I wasn't doing anything wrong.

Reference: https://github.com/faye/faye-websocket-node/pull/50

Currently, stanza.io depends upon faye-websocket 0.10.0, which does not pass the servername parameter to [tls.connect()](https://nodejs.org/docs/latest-v8.x/api/tls.html#tls_tls_connect_options_callback).  This parameter is required to send the server name via the SNI extension.  If the TLS endpoint has multiple vhosts configured and the default one is using an X.509 certificate with a CN that does not match the hostname supplied in the wsURL, the certificate will fail validation.  This ends up manifesting itself in stanza.io by an immediate disconnect event with no further information on the failure.  This issue may be addressed by allowing the user to pass socket options to the faye-websocket constructor or by upgrading to faye-websocket 0.11, which does set the servername parameter by default.

I cannot offer a PR at the moment due to time constraints, but I will follow up later.

Additionally, a comment/question on the disconnected event and error handling:

After modifying lib/transports/websocket.js and adding a console.log() line in the onerror handler for the faye-websocket instance around line 98, I uncovered an UNABLE_TO_VERIFY_LEAF_SIGNATURE error.  It might be nice if the disconnected event included the disconnect reason.  Maybe there's a way to get at it through the client itself rather than via the event, but I didn't see any immediately obvious method for doing so.

**Comment by Reventl0v** [comment]
Hi, I have a semi-related problem, even if I use the last version of stanza.io and faye-websocket-node.
I use prosody and nginx as a reverse proxy for prosody. This is what I get in the logs:

> Dec 23 20:23:15 socket  debug   server.lua: accepted new client connection from ::1:59700 to 5280                                                                                                                                
> Dec 23 20:23:15 http.server     debug   Firing event: GET nebuleuse.grunblatt.org/xmpp-websocket                                                                                                                                 
> Dec 23 20:23:15 c2s260c2870     info    Client connected                                                                                                                                                                         
> Dec 23 20:23:15 c2s260c2870     debug   Sending WebSocket handshake                                                                                                                                                              
> Dec 23 20:23:15 c2s260c2870     info    Client disconnected: connection closed                                                                                                                                                   
> Dec 23 20:23:15 c2s260c2870     debug   Destroying session for (unknown) ((unknown)@(unknown))
> Dec 23 20:23:15 socket  debug   server.lua: closed client handler and removed socket from list                             

It seems the problem is exactly the one described by @eldridge, that is to say an immediate disconnect after connection.

Logging in faye-websocket tells me that the websocket passes from readyState 0 to 1 and then to 3.
Is the commit #243 supposed to fix my problem (or should I open a new bug report) ?

**Comment by eldridge** [comment]
There may be any number of reasons for a disconnect.  The reason can be difficult to get at because stanza.io does not provide much context along with the disconnect event.  I have a local modification that re-emits the event objects delivered to the onerror and onclose handlers from faye-websocket-node.  I've just pushed the change to [my fork](https://github.com/eldridge/stanza.io) if you want to give it a try.  Also make sure you are handling the disconnect event.  E.g.,

`    client.on('disconnected', function (ws, e) {
        console.log(ws);
        console.log(e);
    });
`

I did not include the modifications in my PR because I'm not convinced re-emitting Event/Error objects from dependencies is the right thing to do.  I think I'd rather see stanza.io enumerate the most common causes and emit its own concise yet descriptive error messages.  In any case, the changes in my fork should help you to uncover the underlying cause(s) of your disconnects.

In the case of Prosody, you probably want to [crank your logging up to the "debug" setting](https://prosody.im/doc/logging) during development.  It may also help you identify the cause(s) of the disconnects.

I'm going to close this issue since my specific issue with TLS and SNI is fixed in stanza.io 9.0.1.

**Comment by Reventl0v** [comment]
Hi, thank you for the comment. My prosody was already logging up to the debug setting, so I just tried your fork.

Can I continue bothering you in this issue about my issue, or should we switch to another communication channel? (I get a "code: 1006" in the error from faye-websocket-node and re-emmited by your fork)
