### ISSUE TITLE
adding custom attribute to message not storing message in Archive table on server

### ISSUE THREAD

**Issue by gaurangkela** [legastero/stanza.io#247]
I am working on ionic 3, I want to add some custom attributes while sending message, for that i have followed the steps for creating plugin. my code is as follow...

```
`sendMsg() {
    console.log("Sending message");


    function customMessage(client, stanzas) {
      const NS = 'http://www.w3.org/2005/Atom';
      var types = stanzas.utils;

      const messageAttribute = stanzas.define({
        name: 'messageAttribute',
        element: 'messageAttribute',
        namespace: NS,
        fields: {
          title: types.textSub(NS, 'title'),
          summary: types.textSub(NS, 'summary'),
          published: types.textSub(NS, 'published'),
          updated: types.textSub(NS, 'updated'),
          cont: types.textSub(NS, 'cont')
        }
      });

      stanzas.withMessage((Message) => {
        stanzas.extend(Message, messageAttribute);
      });
    }

    this.client.use(customMessage);

    this.client.sendMessage({
      to: this.recep,
      body: "",
      messageAttribute: {
        'title': "some title",
        'summary': "message",
        'published': "time stamp here",
        'updated': "time stamp here",
        'cont': "cht"
      }
    });
   console.log("Message sent " + this.sMsg);
  }`
```

but doing this way message are not being stored in Archive table on server. that will create a problem to get the history from the server. if we use the simple code then that messages being stored on Archive table on server. simple code as follow..

```
this.client.sendMessage({
      to: this.recep,
      body: this.sMsg    
    });
```
in simple code we can only send message as a string inside body.

**Comment by legastero** [comment]
Your server is only archiving messages which contain a body element with text, which is a pretty common archiving configuration. One trick would be trying to include a dummy body text to trigger message archiving, but you'd have to check if the server is storing and returning the full stanza or just extracting and saving the body text.

You're doing everything correctly with extending Stanza to include the additional fields, but you'll need to adjust your server to get what you want.

**Comment by gaurangkela** [comment]
@legastero thank you for clearification.
