### ISSUE TITLE
unable to get pubsub messages, 'pubsub:event' is not fired

### ISSUE THREAD

**Issue by gaurangkela** [legastero/stanza.io#248]
I am working with pubsub on ionic framework, i'm able to publish message and call getItems from node. but **'pubsub:event' is not fired**. i'm unable to get real-time message which is published on node by other users. my code is as below...

**publish**
```
this.client.publish("pubsub.dev1.internal", 'mynode', {
        json: {
          value: 'Any JSON content could go here'
        }
      }, (err, data) => {
        if (err) {
          console.log(err);
        } else {
          console.log(data)
        }
      });
  }
```

**getItems**

```
this.client.getItems("pubsub.dev1.internal", 'mynode', opts ,
(err, data) => {
        if (err) {
          console.log(err);
        } else {
          console.log(data)
        }
      })
```

**pubsub:event**

```
this.client.on('pubsub:event', function (msg) {
      console.log("pubsub:event");
      console.log(msg);
    });
```

messages which are published are stored in server and when i call getItems i can fetch that messages, but the problem is messages are not received  on real-time using **'pubsub:event'**. can anyone help me to solve this?

**Comment by legastero** [comment]
Just to be sure, you did subscribe to that node first, right?

```this.client.subscribeToNode("pubsub.dev1.internal", "mynode");```

**Comment by gaurangkela** [comment]
i have tried subscribeToNode as below 
```
this.client.subscribeToNode("pubsub.dev1.internal", "mynode", function (err) {
      if (!err) {
        console.log('subscribed');
      }else{
        console.log('subscribe error');
        console.log(err);
      }
    });
```

but i on callback i got error like..

error:{condition: "timeout"}

**Comment by gaurangkela** [comment]
added one second timeout before subscribing and its working..

`setTimeout(() => {
        this.subscribeTONode();
    }, 1000);`
