### ISSUE TITLE
is there any way to remove listener added by client.on(...) ?

### ISSUE THREAD

**Issue by gaurangkela** [legastero/stanza.io#249]
I am working on ionic framework, In my application i have different need for listeners like 'message', 'pubsub:event' so i have added this listeners at multiple place. now i want to remove that listener from particular page when the page is unloaded, but i'm unable to find any method for removing listener. can anyone help me to remove listener?
and i want to know that is it right to add listener multiple time? or it will make any problem?

**Comment by itsazzad** [comment]
```js
apple.off('test');
```

**Comment by gaurangkela** [comment]
do you mean client.off('test).?

**Comment by itsazzad** [comment]
may be

**Comment by gaurangkela** [comment]
its working but it will removing listener from whole app., i want to remove listener from particular page.. do you know how to do so?

**Comment by itsazzad** [comment]
no idea.

**Comment by gaurangkela** [comment]
You need to pass in the listener function to removeListener
`this.client.off('message', this.testFun);`

```
testFun(data) {
    console.log('test complete', data);
}
```
