### ISSUE TITLE
Outgoing messages not received back over websocket connection

### ISSUE THREAD

**Issue by GriffinMartin** [legastero/stanza.io#260]
I am currently working with stanza.io and openfire over a websocket connection.

I have pidgin installed and notice that randomly the client will go offline and reconnect. I have enabled keepalive and am sending a presence every 60 seconds. I have configured openfire to not end sessions and set the timeout to an unlimited duration.

Even when both clients appear online in openfire and pidgin messages are not always received on the other end. In the openfire logs I see the entire conversation, however the incoming message fails to even show up in the websocket logs most of the time resulting in not receiving the message.

If anyone has experience with stanza.io with openfire or has any advice here please let me know.

I've also noticed I randomly stop receiving any incoming events through the websocket connection as well at random points in time.

**Comment by GregDThomas** [comment]
I have no advice, but can confirm that we use stanza.io with Openfire without any issues.

**Comment by GriffinMartin** [comment]
@GregDThomas after further investigation this is openfire related and not stanza.io. Not sure what the cause is as of yet. Going to tweak some config settings.
