### ISSUE TITLE
send raw stanza

### ISSUE THREAD

**Issue by faysal515** [legastero/stanza.io#278]
How can I send raw stanza ? I need to implement message history. my xmpp server supports `urn:xmpp:mam:0` namespace. But the implementation in this library has namespace `urn:xmpp:mam:2`.

So to resolve this problem, I want to send raw query/stanza

**Comment by faysal515** [comment]
nvm, got it. its the `client.sendIq`

**Comment by supertino7** [comment]
> nvm, got it. its the `client.sendIq`

Hi @faysal515 
Would you mind sharing how you did it ? 
My Openfire server doesn't support `urn:xmpp:mam:2` either, and I was looking for a way to change the namespace which seems to be hardcoded
