### ISSUE TITLE
MUC join without message history

### ISSUE THREAD

**Issue by jpablom** [legastero/stanza.io#300]
How can i join a room without receiving message history?

According to [XEP-0045 Multi-User-Chat](https://xmpp.org/extensions/xep-0045.html#enter-managehistory) we need to send a history element with maxchars attribute with value of 0.

I try:
```
Client.joinRoom(room, nick, {
    status: 'online',
    joinMuc: {
        history: {
            maxchars: 0
        }
     }
});
```
but outgoing xml sends an empty history element `<history/>`

Thanks in advance.

**Comment by legastero** [comment]
For now, try passing it as a string (`maxchars: "0"`) instead.

**Comment by jpablom** [comment]
String value works. Thanks!
