### ISSUE TITLE
peerConnectionConfig is not passed to RTCPeerConnection on incoming sessions

### ISSUE THREAD

**Issue by arudnev** [legastero/stanza.io#305]
When outgoing media session is created then `iceServers` and other settings of `peerConnectionConfig` are passed:

https://github.com/legastero/stanza.io/blob/8239e230eb243ad2372cd59ff8a917ea6e5c78d9/src/jingle/SessionManager.js#L114

When incoming session is created then those settings are omitted, at least with default `prepareSession`:

https://github.com/legastero/stanza.io/blob/8239e230eb243ad2372cd59ff8a917ea6e5c78d9/src/jingle/SessionManager.js#L314

It leads to iceServers not being passed to RTCPeerConnection by default on incoming sessions, which most probably was not intentional.

**Comment by legastero** [comment]
Good catch. Fixed and published in 10.2.0
