### ISSUE TITLE
TypeError: e.preventDefault is not a function

### ISSUE THREAD

**Issue by cdecu** [legastero/stanza.io#306]
Hello,  
i am using stanza.io in a node project 
sometime when the connection fail (TimeOut) i got this error 
    
    TypeError: e.preventDefault is not a function 

in stanza.io/transports/websocket.js

        self.conn.onerror = function (e) {
            >>>> e.preventDefault();
            self.emit('disconnected', self);
        };

so i just comment this line :(

**Comment by legastero** [comment]
Thanks! This should be fixed in 10.2.1 now.
