### ISSUE TITLE
how to use stanza with webrtc function  in node ?

### ISSUE THREAD

**Issue by cnmmbd** [legastero/stanza.io#310]
while trying filetransfer in node :
var s=client.jingle.createFileTransferSession(jid);
 it throws error:
ReferenceError: RTCPeerConnection is not defined
    at new ICESession (d:\nodejs\stanza-io\node_modules\stanza.io\jingle\ICESession.js:11:23)
    at new FileTransferSession (d:\nodejs\stanza- 
    io\node_modules\stanza.io\jingle\FileTransferSession.js:102:9)

how to use stanza with webrtc function  in node ?

**Comment by kai670** [comment]
node doesn't include WebRTC support. If you do a google search you can see there are some projects that add WebRTC support for node: https://www.google.com/search?q=node+webrtc&oq=node+webrtc
I haven't tested any of them so I can't provide more information but maybe you can give it a try. But I think there is no relation at all with your problem and stanza.

**Comment by cnmmbd** [comment]
> node doesn't include WebRTC support. If you do a google search you can see there are some projects that add WebRTC support for node: https://www.google.com/search?q=node+webrtc&oq=node+webrtc
> I haven't tested any of them so I can't provide more information but maybe you can give it a try. But I think there is no relation at all with your problem and stanza.

I try filetransfer it in electron and in browser, but I got another error, Uncaught TypeError: Cannot read property 'media' of undefined:
https://github.com/legastero/stanza.io/issues/316

"receivedFile" was fine, but sending file caused that error.
you have any idea of that?

**Comment by legastero** [comment]
Jingle-based features are not supported in node yet. One day, but not today.
