### ISSUE TITLE
Redundant call to RTCPeerConnection.close()

### ISSUE THREAD

**Issue by arudnev** [legastero/stanza.io#313]
It seems that call to `this.pc.close()` is redundant in `MediaSession` https://github.com/legastero/stanza.io/blob/88f45d8ee092e25113c8c4f324bc45dffe6e2cb5/src/jingle/MediaSession.js#L121
as it's already done in 'ICESession'
https://github.com/legastero/stanza.io/blob/88f45d8ee092e25113c8c4f324bc45dffe6e2cb5/src/jingle/ICESession.js#L35
It does not seem to cause any issues on well behaved implementations apart from somewhat confusing logging in native code.

**Comment by legastero** [comment]
Ah, yep. Leftover from refactoring out the ICESession class.

Thanks!
