### ISSUE TITLE
filetransfer with error: Uncaught TypeError: Cannot read property 'media' of undefined

### ISSUE THREAD

**Issue by cnmmbd** [legastero/stanza.io#316]
I added these codes to the demo.html to impl the file transfer, which was copied from the "jingle-interop-demo" 
			function handleFileSelect(evt) {
				var file = evt.target.files[0]; // FileList object
				console.log('file', file.name, file.size, file.type, file.lastModifiedDate);
				var jid = document.getElementById('filepeer').value;
				var sess = client.jingle.createFileTransferSession(jid);
				sess.start(file);
			}
but I got this error:
Uncaught TypeError: Cannot read property 'media' of undefined
    at yr (stanzaio.browser.js:23)
    at vr (stanzaio.browser.js:23)
    at Pr.onSessionAccept (stanzaio.browser.js:23)
    at Ir.processingQueue.d.queue (stanzaio.browser.js:23)
    at stanzaio.browser.js:23
    at Object.process (stanzaio.browser.js:23)
    at stanzaio.browser.js:23
    at stanzaio.browser.js:23
    at stanzaio.browser.js:23
    at p (stanzaio.browser.js:23)
Anyone could tell me how to fix it?

**Comment by legastero** [comment]
Should be fixed in 10.2.6. Thanks!
