### ISSUE TITLE
filetransfer bug : channel.addEventListener('bufferedamountlow', sliceFile);

### ISSUE THREAD

**Issue by cnmmbd** [legastero/stanza.io#318]
FileTransferSession.js line 67:
channel.addEventListener('bufferedamountlow', sliceFile);

"sliceFile" expected a file offset parameter, but in this case, a bufferedamountlow event object was passed in.

**Comment by cnmmbd** [comment]
@legastero

**Comment by legastero** [comment]
Should be fixed in 10.2.8. Thanks!
