### ISSUE TITLE
How to configure Muc light in stanza

### ISSUE THREAD

**Issue by AlexWehe** [legastero/stanza.io#320]
Hi everybody!!!

I would like to know if there exist any possibility to configure the Muc Light module.

https://xmpp.org/extensions/inbox/muc-light.html

Thank you!!!

**Comment by marc0s** [comment]
I'm afraid it's not supported by stanza.io.

**Comment by legastero** [comment]
You would have to write your own plugin and stanza definitions for muc light.

I have no intention of adding support for it in stanza.io.
