### ISSUE TITLE
not compatible with angular-cli  6+

### ISSUE THREAD

**Issue by hansifer** [legastero/stanza.io#323]
Angular 6+ `ng build` does not polyfill node globals and native apis, making it difficult to use this lib in an Angular 6+ project. 

See: https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814

It would be cool if running `npm install stanza` alone provided a browser-ready module that can be imported without the need for the library consumer's module bundler to polyfill native node packages and globals.

**Comment by legastero** [comment]
Any specific globals causing problems that I can start looking for?

**Comment by hansifer** [comment]
Thanks for the quick response. Both `global` and `process` were an issue. I
will do more digging tomorrow and provide details as they emerge.

**Comment by hansifer** [comment]
I've created a simple project with the latest Angular CLI here: https://github.com/hansifer/stanza-test

It imports and uses stanza in `app.component.ts`

`ng build` produces:

```
ERROR in ./node_modules/cipher-base/index.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Hansifer\Documents\Scratch\stanza.io test\stanza-test\node_modules\cipher-base'
ERROR in ./node_modules/hash-base/index.js
Module not found: Error: Can't resolve 'stream' in 'C:\Users\Hansifer\Documents\Scratch\stanza.io test\stanza-test\node_modules\hash-base'
```

Polyfilling stream leads to other errors, including:

`global is not defined at Object../node_modules/buffer/index.js`

**Comment by legastero** [comment]
😬 Looks like this is going to be fun to solve, but we'll get there.

Thank you so much for making that test repo! That helps me tremendously.

**Comment by hansifer** [comment]
Thanks man. I really appreciate your responsiveness. Lemme know how I can help.
