### ISSUE TITLE
searchHistory return 'service-unavailable' on new stanza version

### ISSUE THREAD

**Issue by TheRealTau** [legastero/stanza.io#337]
Hi everyone, I'm trying to get a specific number of messages from a room(muc) history but i'm getting 'service-unavailable' as response. I'm following the example from [here](https://github.com/przemyslawjanpietrzak/stanza.io-examples-tests/blob/master/tests/history.js#L104) and the info from the [docs](https://github.com/legastero/stanza.io/blob/master/docs/Reference.md#clientsearchhistoryopts-cb). My xmpp server is Prosody version 0.10.0 in which the **mam** and **muc** modules are enable.
```
client.searchHistory(
    {
        jid: 'myroom@example.com',
        rsm: {max: 10, before: 'lastMessageId'},
        complete: false
    },
    function(err, resp){
        if(!err){
            console.log("Room history: ", JSON.stringify(resp, null, 4))
        }else{
            console.log("Error message: ", JSON.stringify(err, null, 4))
        }
    }
);
```
With stanza.io@8.4.9 version the searchHistory works fine but with the latest stanza versions (example stanza@11.3.2) I get the error 'service-unavailable'. Am I missing something?

**Comment by marc0s** [comment]
I cannot test with `prosody-0.10` right now, but it's working on my side with `prosody-0.11`.  Are you sure you have the MAM module for MUC enabled?  In `prosody-0.10` is `mod_mam_muc`, IIRC (`0.11`'s is `mod_muc_mam`)

**Comment by TheRealTau** [comment]
I changed my Prosody version to 0.11.2 and it works! for the record I think it has something to do with the mam:0, mam:1 and mam:2. Prosody's 0.10.0 does not support mam:2, [here](https://issues.prosody.im/1129) is more info about it if someone need it. Thanks for the help @marc0s I will close the issue now.
