### ISSUE TITLE
Typo in `role`

### ISSUE THREAD

**Issue by piranna** [legastero/stanza.io#347]
https://github.com/legastero/stanza.io/blob/b8e20ae7f94a1b1fdf7e98071e5317f34b5969a5/src/jingle/MediaSession.js#L96

Shouldn't this be `responder` instead of `resonder`?

**Comment by legastero** [comment]
Already fixed? https://github.com/legastero/stanza.io/issues/303

**Comment by piranna** [comment]
> Already fixed? #303

Seems so, don't know how I ended in that old commit. Clossing.
