### ISSUE TITLE
Comparation too much strict

### ISSUE THREAD

**Issue by piranna** [legastero/stanza.io#349]
https://github.com/legastero/stanza.io/blob/d363d93d371ba21231b23894d63719cc0c662caf/src/jingle/SessionManager.js#L246

By using a strict equal, it assert `session.peerID` and `sender` not only being different strings, but also different objects since it's not doing types cohertion, so if you set `session.peerID` to a `JID` object, it will ALWAYS be different. This needs to be changed to use a plain equal (`==`), or make use of `toString()` method to force it to be a `string`.

**Comment by legastero** [comment]
`peerID` is always expected to be a string.

Fixed session creation methods in 11.3.5 to pull the full JID from a JID object if one was used.

**Comment by piranna** [comment]
Thank you so much by fixing it so fast :-)
